export const types = {
    SEND_REQUEST_GET_ALL_POST: 'SEND_REQUEST_GET_ALL_POST',
    SEND_REQUEST_GET_ALL_POST_SUCCESS: 'SEND_REQUEST_GET_ALL_POST_SUCCESS',
    SEND_REQUEST_GET_ALL_POST_FAILURE: 'SEND_REQUEST_GET_ALL_POST_FAILURE',
    SEND_REQUEST_ADD_POST: 'SEND_REQUEST_ADD_POST',
    SEND_REQUEST_ADD_POST_SUCCESS: 'SEND_REQUEST_ADD_POST_SUCCESS',
    SEND_REQUEST_ADD_POST_FAILED: 'SEND_REQUEST_ADD_POST_FAILED',
}